### ISSUE TITLE
Push Changes错误

### ISSUE THREAD

**Issue by Fullang** [LetsShareAll/Profiles_for_Clash#2]
Run ad-m/github-push-action@master
Push to branch main
remote: Permission to Fullang/Profiles_for_Clash.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/Fullang/Profiles_for_Clash.git/': The requested URL returned error: 403
Error: Invalid exit code: 128
    at ChildProcess.<anonymous> (D:\a\_actions\ad-m\github-push-action\master\start.js:29:21)
    at ChildProcess.emit (node:events:527:28)
    at maybeClose (node:internal/child_process:1092:1[6](https://github.com/Fullang/Profiles_for_Clash/actions/runs/5417126313/jobs/9847739825#step:6:7))
    at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5) 

按照Github Actions的流程做了，secrets and variables-secrets-Repository secrets下有token

**Comment by Shuery-Shuai** [comment]
你在 [`Generate new token`](https://github.com/settings/tokens "Personal Access Tokens (Classic)") 那里是选择的 **[classic](https://github.com/settings/tokens/new "New Personal Access Token (Classic)")**（For general use） 还是 **[beta](https://github.com/settings/tokens "New Fine-grained Personal Access Token")**（Fine-grained, repo-scoped）？

**Comment by Fullang** [comment]
是classic，就勾了repo、workflow、gist。全勾试了一次也不行

**Comment by Fullang** [comment]
对不起误点了close

**Comment by Shuery-Shuai** [comment]
可以参考 [remote: Permission to git denied to github-actions[bot].](https://github.com/ad-m/github-push-action/issues/96) 这个 issue 尝试解决试试。

**Comment by Fullang** [comment]
可以的，在自己的folk，settings-Code and automation-Actions-General-Workflow permissions改为read and write permission就可以成功了
