### ISSUE TITLE
yml

### ISSUE THREAD

**Issue by wxy015513** [LetsShareAll/Profiles_for_Clash#3]
May I ask if running main.py generates a txt file, and how should I do to obtain my own yml file?

**Comment by Shuery-Shuai** [comment]
Could you please explain your issues clearly?

> May I ask if running main.py generates a txt file?

Which text file are you referring to? If you just ask wether a text file will be generated, the answer is yes. And the text files should be placed in `anto_getter/temp`.

> How should I do to obtain my own yml file?

If you want to generate your own profile, changing the `auto_getter/config.yml` will do the trick.

For more details you can explore [the document website (in chinese)](https://pfc.letsshareall.cn).
